wallpaper {
    monitor = eDP-1
    path = ~/.config/backgrounds/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/.config/backgrounds/wallpaper.jpg
    fit_mode = cover
}

ipc = on
splash = false
